### ISSUE TITLE
python modules are not available in an image build with neurodocker and used by singularity

### ISSUE THREAD

**Issue by Hoda1394** [ReproNim/neurodocker#346] opened 2020-05-19 16:38 UTC
I am creating an image with neurodocker that includes python and some modules.  I changed the docker image to singularity with `singularity pull` and tried to run a python script using the image but getting errors saying the modules do not exist! here are commands I am using:
`singularity pull docker://docker-image`
`singularity exec docker-image.sif python python_script`
or 
`singularity shell docker-image.sif`
`python python_script`

An example of error that I am getting:

```
Traceback (most recent call last):
  File "python_script.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by stebo85** [comment] 2020-05-21 23:11
Dear @Hoda1394,

It looks like numpy is not included in the image. Is numpy working in the docker image and only missing in the singularity image? Could you post the neurodocker command line to reproduce the problem?

**Comment by Hoda1394** [comment] 2020-05-22 01:13
Yes, In fact, when I am running the docker image on my laptop I can import numpy but it is missing in the singularity image. Here are the neurodocker commands I used to create the image.

docker run --rm repronim/neurodocker:master generate docker \
  --base=nvidia/cuda:10.1-cudnn7-runtime-ubuntu18.04 --pkg-manager=apt \
  --miniconda create_env=pysci conda_install='python=3.7 pip' \
  --miniconda use_env=pysci \
   pip_install='pillow pandas scipy' \
  --miniconda use_env=pysci pip_install='pydra' activate=true > Dockerfile

**Comment by stebo85** [comment] 2020-05-22 07:44
Dear @Hoda1394 ,

I think I found the cause of the problem: In docker your environment pysci (where numpy is installed) gets correctly loaded when the startup script is called. In the singularity container this doesn't happen when you use exec (it would work when you use run - see https://github.com/ReproNim/neurodocker/issues/242) and you are therefore in the base environment (and there is no numpy in base). A suitable workaround for you might be to install things in base:

   --miniconda use_env=base conda_install='python=3.7 pip' \
   --miniconda use_env=base pip_install='pillow pandas scipy' \
   --miniconda use_env=base pip_install='pydra' \

would that work for you or do you need multiple environments?

**Comment by Hoda1394** [comment] 2020-05-22 13:52
Many thanks for the explanation. It is now clear to me what happens. I can install modules in base env.

**Comment by kaczmarj** [comment] 2020-05-22 14:10
thank you @stebo85 ! i'll close this for now but please reopen or open a new issue if you are running into problems.

**Closed by kaczmarj** 2020-05-22 14:10 UTC
